### ISSUE TITLE
showNotificationsQueue, what does it do?

### ISSUE THREAD

**Issue by Tankbuster0** [HazJ/notificationSystem.VR#3]
Documentation says
showNotificationsQueue = 1; // Show notification queue count in bottom left corner of screen
But I don't see a queue count even when I spam notifications

**Comment by haztakki** [comment]
Hi Tankbuster,
Make sure that you have the following in the description.ext and init.sqf:
```
class RscTitles
{
	#include "notificationSystem\rsc\rsc_notifications.hpp"
};
```
```sqf
"layer_notifications" cutRsc ["rsc_notifications", "PLAIN"];

addMissionEventHandler ["Loaded",
{
	[] spawn
	{
		sleep 2;
		"layer_notifications" cutRsc ["rsc_notifications", "PLAIN"];
	};
}];
```
